### ISSUE TITLE
In-App Message created from a non-UI thread on Android

### ISSUE THREAD

**Issue by petitTrung** [customerio/customerio-android#133]
Version(s) of SDK bug appears: 3.0.0-beta.1

## Current Behavior
I have tested in-app messages by sending some test to my phone : 
The message is displayed in my test, but I got a dangerous error message on the Logcat

![Screenshot 2022-09-19 at 16 37 36](https://user-images.githubusercontent.com/7370259/191043680-43943403-fbe7-4cbf-b7fc-649ce0abc655.png)

It seems that the Banner (or Dialog) is created from a non-UI Thread

## Steps to Reproduce

Phone Model : 
OnePlus 5T - Android 10
Huawei P20 - Android 10
OnePlus 6T - Android 11

App Target : 

Send an in-app `Example Banner` or `Example Welcome`

<img width="478" alt="Screenshot 2022-09-19 at 16 40 38" src="https://user-images.githubusercontent.com/7370259/191044330-5e7d117e-d5b6-43f8-8289-42ba978fb16b.png">

```kotlin
    const val targetSdkVersion = 32
    const val compileSdkVersion = 32
```

## Expected Behavior
 The Overlay should be created from UI Thread

**Comment by Shahroz16** [comment]
Hey @petitTrung, thanks for bringing this to our attention. We are working on a fix and will be rolling it out soon.

**Comment by Shahroz16** [comment]
Hey @petitTrung, closing the loop here. I believe this was fixed and rolled out but the issue never got closed. Feel free to reopen if you still face it.
