### ISSUE TITLE
In App Message Not Appearing

### ISSUE THREAD

**Issue by TimidLupus** [customerio/customerio-android#138]
Version(s) of SDK bug appears: 

    implementation 'io.customer.android:tracking:3.0.0-beta.2'
    implementation 'io.customer.android:messaging-push-fcm:3.0.0-beta.2'
    implementation 'io.customer.android:messaging-in-app:3.0.0-beta.2'

## Current Behavior
In App Message doesn't appear. However I can see following logs:

     I/Gist: Current gist route set to: Home
     I/Gist: Messages timer started
     I/Gist: Fetching user messages
     I/Gist: No messages found for user
     I/Gist: Fetching user messages
     I/Gist: No messages found for user
     I/Gist: Fetching user messages
     I/Gist: No messages found for user

## SDK Initialisation Steps:
Following is in Application class:

    CustomerIO.Builder(
            siteId = "xxxxx",
            apiKey = "xxxxx",
            appContext = this
        )
            .addCustomerIOModule(ModuleMessagingPushFCM())
            .addCustomerIOModule(ModuleMessagingInApp("xxxxxxxxx"))
            .autoTrackScreenViews(true)
            .setRequestTimeout(8000L)
            .build()
            
Following code is called on App Launch (HomeViewModel):

    CustomerIO.instance().identify(
            identifier = profile.userId?.toString()!!,
            attributes = mapOf("email" to (profile.email ?: ""), "firstName" to profile.firstName!!)
        )
        
HomeActivity has label "Home" in manifest

## Expected Behavior
In App Message Should Appear On Home Screen

**Comment by Shahroz16** [comment]
@TimidLupus thank you for writing to us, can you please let me know how did you trigger this message? via campaign or anything else, and whats the status over there?

**Comment by TimidLupus** [comment]
Campaign was used to send the message.
status is: `Sent`

**Comment by Shahroz16** [comment]
Apologies for the late reply, we have rolled out some more fixed to the backend, please can you confirm if its still happening?

**Comment by Shahroz16** [comment]
Closing this, until I hear back that this issue is still happening.
