### ISSUE TITLE
In-App Message action iOS/Android Deep Link reopens the app

### ISSUE THREAD

**Issue by Vukan-Markovic** [customerio/customerio-android#141]
Version(s) of SDK bug appears: 3.0.0

## Current Behavior
We use iOS/Android Deep Link action in the In-App message, but when the app is opened, and we get the in-app message, after pressing **_Yes!_** button which triggers the action, the app then reopens again.

## Steps to Reproduce
<img width="408" alt="Screen Shot 2022-10-14 at 1 11 01 PM" src="https://user-images.githubusercontent.com/30355243/195833362-14124928-1222-4cda-83c8-cafe8b27f7ea.png">

<img width="602" alt="Screen Shot 2022-10-14 at 1 17 32 PM" src="https://user-images.githubusercontent.com/30355243/195834570-c5ec28ac-4aa3-4499-bcba-6e37c99bc701.png">

## Expected Behavior
The app shouldn't reopen because it is already in foreground.

**Any other info?**

**Comment by Shahroz16** [comment]
Hey, @Vukan-Markovic version `3.1.0` is out for Android, which should have the fix for it. Can you please try? feel free to reopen it if it still happens in android.

**Comment by Vukan-Markovic** [comment]
I tried already and it works now, thanks a lot for the fix.
