### ISSUE TITLE
v3.1.0 MessagingPushModuleConfig can not create object due to private constructor

### ISSUE THREAD

**Issue by mbpatel6245** [customerio/customerio-android#149]
**SDK version:** 3.1.0

**Environment:**  Production

**Are logs available?** 

This is compile time issues because MessagingPushModuleConfig we can't use it due to private constructor
**Describe the bug**

For reference of this link https://www.customer.io/docs/sdk/android/migrate-upgrade/ below code snippet attached to the documented site.
`ModuleMessagingPushFCM(
                config = MessagingPushModuleConfig(
                    notificationCallback = this,
                     redirectDeepLinksToOtherApps = false,
                )
            )`
In this code block MessagingPushModuleConfig required 3 param but documentation mentions 2 param that is first bug also  MessagingPushModuleConfig object can't able to create due to private constructor or way of code snippet wrote that is wrong.  
**To Reproduce**

This is compile time issue so it is easily reproduced if you can write code like mention is above link it is easily reproduce the issue.

**Comment by Shahroz16** [comment]
Thanks for reporting this @mbpatel6245, can you please confirm if you are using Kotlin or Java?

**Comment by mbpatel6245** [comment]
Yes I'm using kotlin. And used inside builder similar to mention in documentation.

**Comment by Shahroz16** [comment]
@mbpatel6245 just checked and you are correct its a mistake in `docs`. The builder pattern is being used, hence no access to the private constructor. I'll update the docs meanwhile please use the following. 


```kotlin
CustomerIO.Builder(
            siteId = siteId ?: BuildConfig.SITE_ID,
            apiKey = apiKey ?: BuildConfig.API_KEY,
            appContext = application
        ).apply {
            trackingApiUrl?.let { setTrackingApiURL(trackingApiUrl = it) }
            addCustomerIOModule(ModuleMessagingInApp(BuildConfig.ORGANIZATION_ID))
            addCustomerIOModule(
                ModuleMessagingPushFCM(
                    config = MessagingPushModuleConfig.Builder().apply {
                        setNotificationCallback(this@CustomerIOInitializer)
                        setRedirectDeepLinksToOtherApps(false)
                    }.build()
                )
            )
            setLogLevel(CioLogLevel.DEBUG)
            build()
        }
```

Let me know, if you face any other issue.
