### ISSUE TITLE
Crash on 1 user but he seems blocked on this crash

### ISSUE THREAD

**Issue by arseneHuot** [customerio/customerio-android#248]
**SDK version:** 3.6.5

**Environment:** Production Android

**Are logs available?** 

**Describe the bug**
Crash

**Screenshots**
<img width="1792" alt="Capture d’écran 2023-09-06 à 12 41 33" src="https://github.com/customerio/customerio-android/assets/24872405/a58224ad-d4bc-406d-a9d3-ee9edec0d167">

[com.beebs.mobile_issue_01beba4b5431fe8dc3e200cb66500a7f_crash_session_64F8572302F900013EB935D48388E27F_DNE_0_v2_stacktrace.txt](https://github.com/customerio/customerio-android/files/12536472/com.beebs.mobile_issue_01beba4b5431fe8dc3e200cb66500a7f_crash_session_64F8572302F900013EB935D48388E27F_DNE_0_v2_stacktrace.txt)

**Comment by Shahroz16** [comment]
Hey @arseneHuot thank you for reaching out and apologize that you are facing this issue, We are looking into it right away, can you add some more device context such as memory/storage, etc that might also show on Firebase?
