### ISSUE TITLE
Disabling push notifications

### ISSUE THREAD

**Issue by alenkopic1** [customerio/customerio-android#284]
**SDK version:** 3.8.2

**Are logs available?** 
No

**Describe the issue**
How to disable push notifications in Android? I didn't find anything related on the official [site](https://customer.io/docs/sdk/android/push/).

**Comment by Shahroz16** [comment]
Hey @alenkopic1, thank you for reaching out. Can you please me know about the use case? If you have your push notification implementation than your `FirebaseService` would get the push notifications and not the CustomerIOs service.

**Comment by alenkopic1** [comment]
Hi, thanks for pointing me in the right direction.
This should be done on the FirebaseService.

**Comment by Shahroz16** [comment]
Awesome, thanks for letting us know. Closing this, feel free to open another ticket in case you have more questions.
