### ISSUE TITLE
Ability to set notification icon/color

### ISSUE THREAD

**Issue by atreat** [customerio/customerio-android#83]
The notification icon is currently set to the application icon inside [CustomerIOPushNotificationHandler](https://github.com/customerio/customerio-android/blob/c61a43210c8fb0aed028323768968fb0c967f2e7/messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt#L109). I'd like a way to set a different notification icon as for the majority of cases, the application icon will have a shape background which will be masked on Lollipop+ devices (Display a white circle/square). 

See screenshot:
![Screen Shot 2022-04-10 at 9 44 42 PM](https://user-images.githubusercontent.com/1031555/162656555-0c092355-92ad-454c-8d89-b86d3502c529.png)

# Why are we doing this for our customers? 

--

# How do we test that this change is successful? 

Send test notification when a custom notification icon has been set.

# How are we building this? 

Currently setting the application icon when building the notification:

https://github.com/customerio/customerio-android/blob/1.1.0-alpha.2/messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt#L118

FCM has some documentation that sets defaults when the icon does not exists. Unfortunately because the call to `setSmallIcon` these defaults do not seem to take.

```
<!-- Set custom default icon. This is used when no icon is set for incoming notification messages.
     See README(https://goo.gl/l4GJaQ) for more. -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/ic_stat_ic_notification" />
<!-- Set color used with incoming notification messages. This is used when no color is set for the incoming
     notification message. See README(https://goo.gl/6BKBk7) for more. -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_color"
    android:resource="@color/colorAccent" />
```

I'm not sure if I'd prefer to set ApplicationManifest metadata to set the notification, or if a programmatic method similar to `CustomerIOFirebaseMessagingService.onMessageReceived` in order to achieve this.

**Comment by Shahroz16** [comment]
Thank you for bringing this to our attention @atreat

We can surely look into it and add support for notification icon, you can expect this in the upcoming releases.
